FROM node:22-alpine

WORKDIR /app

# Installer pnpm
RUN npm install -g pnpm@9

# Copier les fichiers de dépendances
COPY package.json pnpm-lock.yaml* ./

# Installer les dépendances
RUN pnpm install

# Copier le code source
COPY . .

EXPOSE 3000

CMD ["pnpm", "dev"]
